/**
 * @format
 */

import {AppRegistry} from 'react-native';
import App from './App'; // Assuming App.js is in the root or ./src
import {name as appName} from './app.json'; // app.json would be created by actual CLI

// Create a dummy app.json if it's missing for this manual setup
// In a real project, app.json is generated by `react-native init`
// For now, we'll just use a hardcoded name if app.json is not present.
const effectiveAppName = appName || 'VaMiDzoRider';

AppRegistry.registerComponent(effectiveAppName, () => App);
